### ISSUE TITLE
Create Exchange model CRUD

### ISSUE THREAD

**Issue by ferdn4ndo** [ferdn4ndo/candlestick-data-lake#7]
Attributes:

* id
* code (must be somehow identified inside the implementations of `ExchangeService`)
* name

**Comment by pxotox** [comment]
As the exchange depends on the internal implementation of `ExchangeService`, do you all agree that we shouldn't have a CRUD for this and it should be added by migrations only?

**Comment by ferdn4ndo** [comment]
> As the exchange depends on the internal implementation of `ExchangeService`, do you all agree that we shouldn't have a CRUD for this and it should be added by migrations only?

Totally agree. Closing this one.
